

target_item = [
    "codice_identificativo_della_cav",
    "codice_identificatico_catasto_s",
    "denominazione_comunemente_usata",
    "altra_codifica",
    "altro_riferimento_di_codifica",
    "compilatore",
    "compilatore_other",
    "data_di_prima_compilazione",
    "data_ultimo_aggiornamento",
    "regione",
    "provincia",
    "comune",
    "localit_frazionevia",
    "cosa_rappresenta_per_la_cavit_i",
    "cosa_rappresenta_other",
    "latitudine_dd",
    "longitudine_dd",
    "latitudine_m",
    "longitudine_m",
    "fuso_di_proiezione_utm_",
    "tipologia_primaria",
    "tipologia",
    "epoca_di_realizzazione",
    "uso_oginario",
    "uso_attuale",
    "modalit_di_accesso",
    "modalit_di_accesso_other",
    "tipologia_di_accesso",
    "tipologia_di_accesso_other",
    "sviluppo_della_cavit_o_della_re",
    "estensione_areale",
    "estensione_lineare",
    "prosecuzioni_rispetto_allo_svil",
    "elementi_accessori_propri_della",
    "pozzi_di_accesso",
    "presenza_rifiuti",
    "area_coinvolta",
    "vincolo_territoriale",
    "propriet_",
    "note_descrittive",
    "tipologia_di_materiale_scavo",
    "grado_di_addensamento",
    "grado_di_fratturazione",
    "grado_di_cementazione",
    "descrizione",
    "indizi_di_instabilit_in_superfi",
    "indizi_di_instabilit_in_cavit_",
    "presenza_di_acqua",
    "presenza_di_gas",
    "altro",
    "altezza_minima_della_cavit_",
    "altezza_massima_della_cavit_",
    "spessore_minimo_in_voltacalotta",
    "spessore_massimo_in_voltacalott",
    "profondit_minima_della_voltacal",
    "profondit_massima_della_voltaca",
    "profondit_minima_del_piano_di_c",
    "profondit_massima_del_piano_di_",
    "interventi_strutturali_effettua",
    "condizioni_generali_della_cavit",
    "note_generali",
    "riferimenti_bibliografici",
    "created_date",
    "created_user",
    "last_edited_date",
    "last_edited_user",
    "quota",
    "attach1",
    "descrizione1",
    "attach2",
    "descrizione2"
]

source_item = [
    'codice_identificativo_della_cav',
    'codice_SSI',
    'regione',
    'provincia',
    'comune',
    'localit_frazionevia',
    'tipologia_primaria',
    'tipologia',
    'denominazione_comunemente_usata',
    'note_descrittive',
    'data_di_prima_compilazione',
    'data_ultimo_aggiornamento',
    'created_user',
    'created_date',
    'last_edited_user',
    'last_edited_date',
    'latitudine',
    'longitudine',
    'quota',
    'attach1',
    'descrizione1',
    'attach2',
    'descrizione2',
    'riferimenti_bibliografici'
]

mapping_item = {
    'codice_SSI' : "codice_identificatico_catasto_s",
    'denominazione_comunemente_usata' : "denominazione_comunemente_usata",
    'data_di_prima_compilazione' : "data_di_prima_compilazione",
    'data_ultimo_aggiornamento' : "data_ultimo_aggiornamento",
    'regione' : "regione",
    'provincia' : "provincia",
    'comune' : "comune",
    'localit_frazionevia' : "localit_frazionevia",
    'latitudine' : "latitudine_dd",
    'longitudine' : "longitudine_dd",
    'tipologia_primaria' : "tipologia_primaria",
    'tipologia' : "tipologia",
    'note_descrittive' : "note_generali",
    'riferimenti_bibliografici' : "riferimenti_bibliografici",
    'created_date' : "created_date",
    'created_user' : "created_user",
    'last_edited_date' : "last_edited_date",
    'last_edited_user' : "last_edited_user",
    'quota' : "quota",
    'attach1' : "attach1",
    'descrizione1' : "descrizione1",
    'attach2' : "attach2",
    'descrizione2' : "descrizione2"
}

final_item = [
    "SHAPE@",
    "codice_identificatico_catasto_s",
    "denominazione_comunemente_usata",
    "data_di_prima_compilazione",
    "data_ultimo_aggiornamento",
    "regione",
    "provincia",
    "comune",
    "localit_frazionevia",
    "latitudine_dd",
    "longitudine_dd",
    "tipologia_primaria",
    "tipologia",
    "note_generali",
    "riferimenti_bibliografici",
    "created_date",
    "created_user",
    "last_edited_date",
    "last_edited_user",
    "quota",
    "attach1",
    "descrizione1",
    "attach2",
    "descrizione2"
]